services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi-backend
    ports:
      - "${BACKEND_PORT:-8000}:${BACKEND_PORT:-8000}"
    networks:
      - mynetwork
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://${BACKEND_HOST:-0.0.0.0}:${BACKEND_PORT:-8000}/health')"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL}
        BACKEND_HOST: ${BACKEND_HOST}
        BACKEND_PORT: ${BACKEND_PORT}
    container_name: frontend-app
    ports:
      - "${FRONTEND_PORT:-80}:${FRONTEND_PORT:-80}"
    networks:
      - mynetwork
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${FRONTEND_HOST:-0.0.0.0}:${FRONTEND_PORT:-80}"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  mynetwork:
    driver: bridge