services:
  backend:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    container_name: fastapi-backend
    ports:
      - "${BACKEND_PORT:-8000}:${BACKEND_PORT:-8000}"
    networks:
      - mynetwork
    restart: always
    depends_on:
      - frontend
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${BACKEND_HOST:-0.0.0.0}:${BACKEND_PORT:-8000}/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    container_name: frontend-app
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    networks:
      - mynetwork
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${FRONTEND_HOST:-0.0.0.0}:${FRONTEND_PORT:-3000}"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  mynetwork:
    driver: bridge