version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    networks:
      - mynetwork

  frontend:
    build:
      context: ./frontend 
      dockerfile: frontend.dockerfile
    container_name: frontend-app
    ports:
      - "3000:80"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge